### ISSUE TITLE
Disable vi mode for confirmation

### ISSUE THREAD

**Issue by weilbith** [nocttuam/autodotenv#1]
Hey,

first thanks for the nice plugin. I like the option to get asked for a confirmation. But there is also the issue for me. I'm using the VI mode of Zsh. It took me a while to figure out why it does not work to type anything for the prompt of this plugin. In the end I was in need to first enter insert mode. This differs from any other prompt I know and is kinda cumbersome. Do you think you can fix the confirmation so it simply works without?

**Comment by nocttuam** [comment]
Thanks for using this plugin. My project is a Zsh plugin inspired in [dotenv plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/dotenv).

In the past, the original plugin did not have a confirmation message, so I created this plugin.

Now they have this functionality and with some extra settings. [If you don't want the confirmation message, you can disable](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/dotenv#zsh_dotenv_prompt)

I suggest taking a look at it.

**Comment by weilbith** [comment]
Cool thanks for the hint. Since I use already some plugins from `oh-my-zsh` I just with that one.
